# Generated by Django 6.0.2 on 2026-02-26 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SourceFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("doi", models.CharField(blank=True, max_length=255)),
                ("s3_key", models.CharField(blank=True, max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("stored", "Stored"),
                            ("parsed", "Parsed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "source file",
                "verbose_name_plural": "source files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tags_pubmed",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of PubMed-style tags (list of strings)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="ingestion.sourcefile",
                    ),
                ),
            ],
            options={
                "verbose_name": "file metadata",
                "verbose_name_plural": "file metadata",
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Content of the chunk (e.g. one line)"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in the original file"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_chunks",
                        to="ingestion.sourcefile",
                    ),
                ),
            ],
            options={
                "verbose_name": "document chunk",
                "verbose_name_plural": "document chunks",
                "ordering": ["source_file", "order"],
            },
        ),
    ]
