# Generated by Django 6.0.2 on 2026-03-18 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_documentchunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='chunk_type',
            field=models.CharField(choices=[('text', 'Text'), ('table', 'Table'), ('figure', 'Figure'), ('other', 'Other')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='end_offset',
            field=models.PositiveIntegerField(blank=True, help_text='Character or token end offset in the source.', null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='start_offset',
            field=models.PositiveIntegerField(blank=True, help_text='Character or token start offset in the source.', null=True),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doi', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('authors_raw', models.TextField(blank=True, help_text='Authors as a single string (e.g. comma-separated).')),
                ('published_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='Journal or source name.', max_length=512)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('document_type', models.CharField(blank=True, help_text='Type/ontology label (e.g. article, report).', max_length=128)),
                ('external_ids', models.JSONField(blank=True, default=dict, help_text='Structured external IDs (e.g. pmid, arxiv_id) for providers.')),
                ('raw_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='ingestion.sourcefile')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ingestion.document'),
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_type', models.CharField(choices=[('doi', 'DOI'), ('upload', 'Upload'), ('provider_specific', 'Provider-specific')], default='doi', max_length=32)),
                ('input_identifier', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('pipeline_version', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='ingestion.document')),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='ingestion.sourcefile')),
            ],
            options={
                'verbose_name': 'ingestion run',
                'verbose_name_plural': 'ingestion runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('format', models.CharField(choices=[('markdown', 'Markdown'), ('json', 'JSON'), ('html', 'HTML')], default='markdown', max_length=20)),
                ('storage_key', models.CharField(max_length=512)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('parser_name', models.CharField(blank=True, max_length=64)),
                ('parser_config', models.CharField(blank=True, max_length=256)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parsed_artifacts', to='ingestion.document')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_artifacts', to='ingestion.sourcefile')),
            ],
            options={
                'verbose_name': 'parsed artifact',
                'verbose_name_plural': 'parsed artifacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='primary_parsed_artifact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_as_primary', to='ingestion.parsedartifact'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='parsed_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='ingestion.parsedartifact'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['language', 'document_type'], name='ingestion_d_languag_ea7e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['published_date'], name='ingestion_d_publish_710935_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('doi__isnull', False), models.Q(('doi', ''), _negated=True)), fields=('doi',), name='ingestion_document_doi_unique_non_empty'),
        ),
    ]
