# Generated by Django 6.0.3 on 2026-04-15 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_parsed_artifact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentchunk',
            options={'ordering': ['document', 'order'], 'verbose_name': 'document chunk', 'verbose_name_plural': 'document chunks'},
        ),
        migrations.RemoveField(
            model_name='sourcefile',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='source_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='ingestion.sourcefile'),
        ),
    ]
