# Generated by Django 6.0.3 on 2026-04-15 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0005_document_source_file_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('stage', models.CharField(choices=[('acquire', 'Acquire'), ('store', 'Store'), ('parse', 'Parse'), ('chunk', 'Chunk'), ('done', 'Done')], default='acquire', max_length=20)),
                ('success_kind', models.CharField(blank=True, choices=[('metadata_only', 'Metadata Only'), ('full', 'Full')], max_length=20, null=True)),
                ('input_type', models.CharField(choices=[('doi', 'DOI'), ('pdf_upload', 'PDF Upload')], max_length=20)),
                ('input_identifier', models.CharField(help_text='DOI string or upload reference', max_length=512)),
                ('provider', models.CharField(blank=True, help_text='Metadata API used', max_length=255, null=True)),
                ('raw_provider_payload', models.JSONField(blank=True, help_text='Verbatim API response from the metadata provider', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_stage', models.CharField(blank=True, max_length=20, null=True)),
                ('pipeline_version', models.CharField(max_length=64)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='ingestion.document')),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_runs', to='ingestion.sourcefile')),
            ],
            options={
                'verbose_name': 'ingestion run',
                'verbose_name_plural': 'ingestion runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
