# Generated by Django 6.0.4 on 2026-04-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0006_ingestion_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of keywords associated with the document.",
            ),
        ),
    ]
