# Generated by Django 6.0.4 on 2026-04-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0007_document_keywords"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=512)),
                (
                    "orcid",
                    models.CharField(
                        blank=True,
                        help_text="ORCID identifier (e.g. 0000-0001-2345-6789). Unique when set.",
                        max_length=19,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "author",
                "verbose_name_plural": "authors",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="authors",
            field=models.ManyToManyField(
                blank=True, related_name="documents", to="ingestion.author"
            ),
        ),
    ]
